spring:
  application:
    name: youbetterread
  codec:
    max-in-memory-size: 10MB

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.dd7abc86d9420bc2
            client-secret: a5129dfaf35b8bfe88deedde7f7ffa87204a7a4d
  data:
    cassandra:
      keyspace-name: main
      username: XtvYRrKgjQmxOaspwhzzJXHI
      password: TC3NeJpDbhfeIxcdZctb7jQUWrs1f24ps6OmJuTS0viBAApPfn+9bkvUXBURGQ8zrjID3YJZ8zPlbYdDAHfrEP8UvUZxh73pkP1gGI+kcILxRDuHGUIQAK31qdJw2L10
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: secure-connect-betterread.zip

astra.db:
  id: 51f9ee3c-14a9-411c-a3a9-566183a58c6b
  region: asia-south1
  keyspace: main
  application.token: AstraCS:XtvYRrKgjQmxOaspwhzzJXHI:92f874d1df3064785b2b2ec30bc06c517b6927bfff6c818baff0f996a0982afc
